# ---
# see - http://docs.ansible.com/ansible/galaxy.html#advanced-control-over-role-requirements-files
# ---
---
# mackerel-agent
- src: mackerelio.mackerel-agent
  version: v0.8.4

# logwatch
- src: kalos.logwatch
  version: v1.1.0

# ssmtp
- src: franklinkim.ssmtp
  version: 1.0.1

