---
- name: Set up my home server.
  hosts: home_server
  become: yes

  vars_prompt:
    - name: "ssh_port_custom"
      prompt: "specify the port number of ssh"
      private: yes
      default: 22

    - name: "ssmtp_auth_password"
      prompt: "enter the password for the SMTP authentication password"
      private: yes
      confirm : yes

    - name: "mydns_pw"
      prompt: "enter the master password for the MyDNS"
      private: yes
      confirm : yes

  roles:
    # - sample
    - common
    - ssh
    - samba
    - ufw
    - datadog-agent
    - docker
    - docker-compose
    - mackerel.mackerel-agent
    - kalos.logwatch
    - franklinkim.ssmtp
    - cron


  # 外付けHDDにCronでバックアップ
  # -> 自動マウントするのに fstab に外付けデバイスの uuid を記入する必要があるので手動でやろう

