---
- name: Set up my home server.
  hosts: home_server
  sudo: yes

  vars_prompt:
    - name: "ssh_port_custom"
      prompt: "specify the port number of ssh"
      private: yes
      default: 22

  roles:
    - common
    - samba
    - ufw


  # 外付けHDDにCronでバックアップ
  # DDNSポーリング
  # ログをメールに送信

  # Ruby on Rails

