---
- name: Set up my home server.
  hosts: home_server
  sudo: yes

  vars_prompt:
    - name: "ssh_port_custom"
      prompt: "specify the port number of ssh"
      private: yes
      default: 22

  roles:
    # - sample
    - common
    - samba
    - ufw
    - docker


  # DDNSポーリング
  # ログをメールに送信

  # Ruby on Rails
  # -> Dockerfile でやろう
  # 外付けHDDにCronでバックアップ
  # -> 自動マウントするのに fstab に外付けデバイスの uuid を記入する必要があるので手動でやろう

