---
- name: Set up my home server.
  hosts: home_server
  sudo: yes

  vars_prompt:
    - name: "ssh_port_custom"
      prompt: "specify the port number of ssh"
      private: yes
      default: 22

    - name: "ssmtp_auth_password"
      prompt: "enter the password for the SMTP authentication user"
      private: yes
      confirm : yes

  roles:
    # - sample
    - common
    - ssh
    - samba
    - ufw
    - docker
    - mackerel.mackerel-agent
    - kalos.logwatch
    - franklinkim.ssmtp


  # DDNSポーリング

  # 外付けHDDにCronでバックアップ
  # -> 自動マウントするのに fstab に外付けデバイスの uuid を記入する必要があるので手動でやろう

