---
- name: Install samba packages
  apt:
    update_cache: yes
    name:
      - samba
      - samba-common
      - samba-common-bin

- name: Create root samba directories
  file:
    path: '{{ samba_path }}'
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create samba share directories
  file:
    path: '{{ samba_shares_path }}'
    state: directory
    owner: root
    group: root
    mode: 0777

- name: Configure samba server
  template:
    src: etc/samba/smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644
  notify: Reload samba

- name: Daily backup for samba
  cron:
    name: "Mirror samba"
    special_time: daily
    job: "[ -d /external-volume-01 ] || exit 0; rsync -av --delete {{ samba_path }} /external-volume-01"

