---

# Backup Server
samba_backup_server: '192.168.0.9'
samba_backup_server_dst_dir: 'NetBackup/backupdata'
samba_backup_server_user: 'dsk'
samba_backup_server_user_private_ssh_key: '/home/dsk/.ssh/id_rsa_synology'

# Location of Samba shares
samba_path: '/srv/samba'
samba_shares_path: '{{ samba_path }}/share'

samba_workgroup: 'WORKGROUP'
samba_netbios_name: '{{ ansible_hostname }}'
samba_server_string: '%h file server'

# Name of the /etc/init.d/ service script
samba_service_name: 'smbd'

# Which hash variable is used to configure [global] section in smb.conf
samba_global: '{{ samba_default_global }}'

# You can specify additional options in a separate hash
samba_global_custom: False

# Which hash of hashes is used to configure shares in smb.conf
samba_shares: '{{ samba_default_shares }}'

# Default [global] configuration
samba_default_global:

  # Browsing / Identification
  workgroup: '{{ samba_workgroup | default("WORKGROUP") }}'
  netbios_name: '{{ samba_netbios_name | default(ansible_hostname) }}'
  server_string: '{{ samba_server_string | default("%h file server") }}'

  # Logs / Accounting
  log_file: '/var/log/samba/log.%m'
  max_log_size: '1000'
  syslog: '0'

  # Authentication
  server_role: 'standalone server'
  security: 'user'
  encrypt_passwords: 'true'
  passdb_backend: 'tdbsam'
  obey_pam_restrictions: 'yes'
  unix_password_sync: 'no'
  invalid_users: 'root bin daemon adm sync shutdown halt mail news uucp proxy www-data backup sshd'
  pam_password_change: 'no'
  map_to_guest: 'bad user'
  guest_account: 'nobody'

  # File system / Directories
  unix_charset: 'UTF8'
  locking: 'yes'
  wide_links: 'no'
  browseable: 'no'
  create_mask: '0660'
  directory_mask: '0755'
  dont_descend: './lost+found' # 共有ディレクトリの内容を表示しないディレクトリのリストを指定する
  use_sendfile: 'no'
  hide_unreadable: 'yes'
  hide_files: '/.*/lost+found/'

  # Networking / Connections
  socket_options: 'TCP_NODELAY'
  deadtime: '10'
  wins_support: 'no'
  dns_proxy: 'no'
  name_resolve_order: 'lmhosts host wins bcast'

  # Disable printing by default
  # printing: 'bsd'
  load_printers: 'no'
  # printcap_name: '/etc/printcap'
  show_add_printer_wizard: 'no'
  disable_spoolss: 'yes' # プリンタ共有無効化

  # iOSからファイルコピーできるように
  vfs_objects: 'catia fruit streams_xattr'

# Hash of hashes of default shares
samba_default_shares:

  'share':
    comment: 'Share Directory'
    path: '{{ samba_shares_path }}'
    browseable: 'yes'
    create_mode: '2777'
    directory_mode: '2777'
    create_mask: '0755'
    read_only: 'no'
    guest_ok: 'yes'
    public: 'yes'

