---
- name: Add default ssh port
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "Port 22"
    state: present

- name: Add custom ssh port
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "Port {{ ssh_port_custom }}"
    state: present

- name: Disable password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "PasswordAuthentication no"
    state: present
  notify: Restart ssh

