---
- name: Install ufw packages
  apt:
    name: ufw

- name: Deny everything and enable UFW
  ufw:
    state: enabled
    policy: deny

- name: Set logging
  ufw:
    logging: 'on'

# see - http://unixluser.org/techmemo/ident/
- name: mail/ftp が遅くならないように 113 port は reject にしとくと良いっぽい 
  ufw:
    rule: reject
    port: auth
    log: yes

# ufw supports connection rate limiting, which is useful for protecting
# against brute-force login attacks. ufw will deny connections if an IP
# address has attempted to initiate 6 or more connections in the last
# 30 seconds. See  http://www.debian-administration.org/articles/187
# for details. Typical usage is:
- name: Protecting against brute-force login attacks
  ufw:
    rule: limit
    port: ssh
    proto: tcp

# ---
# Settings of apps or services.
# App setting files are /etc/ufw/applications.d/.

# Allow OpenSSH
# limit は30秒間に6回アクセスしてきた IP の接続を一定時間拒否する
- name: Protecting against brute-force login attacks using OpenSSH
  ufw:
    rule: limit
    name: OpenSSH

- name: Allow OpenSSH-custom
  ufw:
    rule: allow
    port: '{{ ssh_port_custom }}'

- name: Allow all access from RFC1918(IPv4) networks to this host
  ufw:
    rule: allow
    from_ip: '{{ local_network_ipv4 }}'
    name: Samba

- name: Allow all access from RFC4193(IPv6) networks to this host
  ufw:
    rule: allow
    from_ip: '{{ local_network_ipv6 }}'
    name: Samba

- name: Allow HTTP/HTTPS
  ufw:
    rule: allow
    port: 80,443
    proto: tcp

- name: Configure UFW
  template:
    src: etc/default/ufw.j2
    dest: /etc/default/ufw
    owner: root
    group: root
    mode: 0644
    backup: yes

