---
- name: Install common packages
  apt:
    update_cache: yes
    name:
      - ntp
      - git
      - lm-sensors
  notify: Restart ntp
  tags: common-packages

- name: set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

