---
- name: Install docker
  apt:
    update_cache: yes
    name: docker.io

- name: Set up docker group for to avoid having to use sudo.
  user:
    name: '{{ docker_user }}'
    groups: docker
    append: yes

# ---
# see - https://docs.docker.com/engine/installation/linux/ubuntu/#os-requirements
# ---
#
# Ubuntu20.04ではsudo apt install -y docker.ioで最新版をインストールできるようになっていた。
# なのでDocker公式の手順は不要だが、roleの参考に残しておく。
# - name : Purge the old docker if it exists.
#   apt:
#     name:
#       - docker
#       - docker-engine
#       - docker.io
#       - containerd
#       - runc
#     state: absent
#     purge: yes
#
# - name: Update the apt package index and install packages to allow apt to use a repository over HTTPS
#   apt:
#     update_cache: yes
#     name:
#       - apt-transport-https
#       - ca-certificates
#       - curl
#       - gnupg-agent
#       - software-properties-common
#
# - name: Add Docker’s official GPG key.
#   shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#   register: result
#   changed_when: result.rc != 0
#
# - name: Set kernel release.
#   shell: /usr/bin/lsb_release -cs
#   register: lsb_release
#   changed_when: "lsb_release.rc != 0"
#
# # NOTE: Ubuntu20.04 focal のリポジトリがなくてここでエラーになる
# - name: Add the stable repository.
#   apt_repository:
#     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable
#     state: present
#
# - name: Update the apt package index, and install the latest version of Docker Engine and containerd, or go to the next step to install a specific version.
#   apt:
#     update_cache: yes
#     name:
#       - docker-ce
#       - docker-ce-cli
#       - containerd.io
#     notify: Restart docker
#
# - name: Set up docker group for to avoid having to use sudo.
#   user:
#     name: '{{ docker_user }}'
#     groups: docker
#     append: yes

